# Generated by Django 4.0.4 on 2022-05-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('type', models.CharField(max_length=20)),
                ('size_small', models.IntegerField(blank=True, null=True)),
                ('price_small', models.IntegerField(blank=True, null=True)),
                ('size_big', models.IntegerField(blank=True, null=True)),
                ('price_big', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
